import type { Stock } from "@/types/stock"

export const KOSPI200_STOCKS: Stock[] = [
  { symbol: "005930.KS", nameKo: "삼성전자", nameEn: "Samsung Electronics" },
  { symbol: "000660.KS", nameKo: "SK하이닉스", nameEn: "SK Hynix" },
  { symbol: "066570.KS", nameKo: "LG전자", nameEn: "LG Electronics" },
  { symbol: "009150.KS", nameKo: "삼성전기", nameEn: "Samsung Electro-Mechanics" },
  { symbol: "012450.KS", nameKo: "한화에어로스페이스", nameEn: "Hanwha Aerospace" },
  { symbol: "011200.KS", nameKo: "HMM", nameEn: "HMM" },
  { symbol: "010140.KS", nameKo: "삼성중공업", nameEn: "Samsung Heavy Industries" },
  { symbol: "000810.KS", nameKo: "삼성화재해상보험", nameEn: "Samsung Fire & Marine Insurance" },
  { symbol: "000720.KS", nameKo: "현대건설", nameEn: "Hyundai Engineering & Construction" },
  { symbol: "011170.KS", nameKo: "롯데케미칼", nameEn: "Lotte Chemical" },
  { symbol: "086790.KS", nameKo: "하나금융지주", nameEn: "Hana Financial Group" },
  { symbol: "086280.KS", nameKo: "현대글로비스", nameEn: "Hyundai Glovis" },
  { symbol: "010130.KS", nameKo: "고려아연", nameEn: "Korea Zinc" },
  { symbol: "012330.KS", nameKo: "현대모비스", nameEn: "Hyundai Mobis" },
  { symbol: "005380.KS", nameKo: "현대차", nameEn: "Hyundai Motor" },
  { symbol: "004020.KS", nameKo: "현대제철", nameEn: "Hyundai Steel" },
  { symbol: "096770.KS", nameKo: "SK이노베이션", nameEn: "SK Innovation" },
  { symbol: "016360.KS", nameKo: "삼성증권", nameEn: "Samsung Securities" },
  { symbol: "105560.KS", nameKo: "KB금융", nameEn: "KB Financial Group" },
  { symbol: "090430.KS", nameKo: "아모레퍼시픽", nameEn: "Amorepacific" },
  { symbol: "035250.KS", nameKo: "강원랜드", nameEn: "Kangwon Land" },
  { symbol: "051910.KS", nameKo: "LG화학", nameEn: "LG Chem" },
  { symbol: "029780.KS", nameKo: "삼성카드", nameEn: "Samsung Card" },
  { symbol: "032830.KS", nameKo: "삼성생명", nameEn: "Samsung Life Insurance" },
  { symbol: "028050.KS", nameKo: "삼성E&A", nameEn: "Samsung E&A" },
  { symbol: "042660.KS", nameKo: "한화오션", nameEn: "Hanwha Ocean" },
  { symbol: "128940.KS", nameKo: "한미약품", nameEn: "Hanmi Pharm" },
  { symbol: "006800.KS", nameKo: "미래에셋증권", nameEn: "Mirae Asset Securities" },
  { symbol: "036570.KS", nameKo: "엔씨소프트", nameEn: "NCsoft" },
  { symbol: "006400.KS", nameKo: "삼성SDI", nameEn: "Samsung SDI" },
  { symbol: "055550.KS", nameKo: "신한지주", nameEn: "Shinhan Financial Group" },
  { symbol: "005830.KS", nameKo: "DB손해보험", nameEn: "DB Insurance" },
  { symbol: "009830.KS", nameKo: "한화솔루션", nameEn: "Hanwha Solutions" },
  { symbol: "000270.KS", nameKo: "기아", nameEn: "Kia" },
  { symbol: "034220.KS", nameKo: "LG디스플레이", nameEn: "LG Display" },
  { symbol: "011070.KS", nameKo: "LG이노텍", nameEn: "LG Innotek" },
  { symbol: "017670.KS", nameKo: "SK텔레콤", nameEn: "SK Telecom" },
  { symbol: "010950.KS", nameKo: "S-Oil", nameEn: "S-Oil" },
  { symbol: "010120.KS", nameKo: "LS ELECTRIC", nameEn: "LS Electric" },
  { symbol: "028260.KS", nameKo: "삼성물산", nameEn: "Samsung C&T" },
  { symbol: "033780.KS", nameKo: "KT&G", nameEn: "KT&G" },
  { symbol: "032640.KS", nameKo: "LG유플러스", nameEn: "LG Uplus" },
  { symbol: "035420.KS", nameKo: "NAVER", nameEn: "Naver" },
  { symbol: "078930.KS", nameKo: "GS", nameEn: "GS Holdings" },
  { symbol: "030200.KS", nameKo: "KT", nameEn: "KT Corporation" },
  { symbol: "003550.KS", nameKo: "LG", nameEn: "LG Corp" },
  { symbol: "003490.KS", nameKo: "대한항공", nameEn: "Korean Air Lines" },
  { symbol: "000150.KS", nameKo: "두산", nameEn: "Doosan" },
  { symbol: "034730.KS", nameKo: "SK", nameEn: "SK Holdings" },
  { symbol: "051900.KS", nameKo: "LG생활건강", nameEn: "LG Household & Health Care" },
  { symbol: "021240.KS", nameKo: "코웨이", nameEn: "Coway" },
  { symbol: "015760.KS", nameKo: "한국전력공사", nameEn: "Korea Electric Power (KEPCO)" },
  { symbol: "036460.KS", nameKo: "한국가스공사", nameEn: "Korea Gas Corporation" },
  { symbol: "005490.KS", nameKo: "POSCO홀딩스", nameEn: "POSCO Holdings" },
  { symbol: "000100.KS", nameKo: "유한양행", nameEn: "Yuhan Corporation" },
  { symbol: "047050.KS", nameKo: "포스코인터내셔널", nameEn: "POSCO International" },
  { symbol: "011790.KS", nameKo: "SKC", nameEn: "SKC" },
  { symbol: "071050.KS", nameKo: "한국금융지주", nameEn: "Korea Investment Holdings" },
  { symbol: "009540.KS", nameKo: "HD한국조선해양", nameEn: "HD Korea Shipbuilding & Offshore Engineering" },
  { symbol: "024110.KS", nameKo: "기업은행", nameEn: "Industrial Bank of Korea" },
  { symbol: "034020.KS", nameKo: "두산에너빌리티", nameEn: "Doosan Enerbility" },
  { symbol: "005940.KS", nameKo: "NH투자증권", nameEn: "NH Investment & Securities" },
  { symbol: "003230.KS", nameKo: "삼양식품", nameEn: "Samyang Foods" },
  { symbol: "039490.KS", nameKo: "키움증권", nameEn: "Kiwoom Securities" },
  { symbol: "042700.KS", nameKo: "한미반도체", nameEn: "Hanmi Semiconductor" },
  { symbol: "047810.KS", nameKo: "한국항공우주산업", nameEn: "Korea Aerospace Industries" },
  { symbol: "138040.KS", nameKo: "메리츠금융지주", nameEn: "Meritz Financial Group" },
  { symbol: "161390.KS", nameKo: "한국타이어앤테크놀로지", nameEn: "Hankook Tire & Technology" },
  { symbol: "180640.KS", nameKo: "한진칼", nameEn: "Hanjin Kal" },
  { symbol: "064350.KS", nameKo: "현대로템", nameEn: "Hyundai Rotem" },
  { symbol: "018260.KS", nameKo: "삼성에스디에스", nameEn: "Samsung SDS" },
  { symbol: "079550.KS", nameKo: "LIG디펜스앤에어로스페이스", nameEn: "LIG Defense & Aerospace" },
  { symbol: "003670.KS", nameKo: "포스코퓨처엠", nameEn: "POSCO Future M" },
  { symbol: "022100.KS", nameKo: "포스코DX", nameEn: "POSCO DX" },
  { symbol: "035720.KS", nameKo: "카카오", nameEn: "Kakao" },
  { symbol: "068270.KS", nameKo: "셀트리온", nameEn: "Celltrion" },
  { symbol: "207940.KS", nameKo: "삼성바이오로직스", nameEn: "Samsung Biologics" },
  { symbol: "241560.KS", nameKo: "두산밥캣", nameEn: "Doosan Bobcat" },
  { symbol: "329180.KS", nameKo: "HD현대중공업", nameEn: "HD Hyundai Heavy Industries" },
  { symbol: "267260.KS", nameKo: "HD현대일렉트릭", nameEn: "HD Hyundai Electric" },
  { symbol: "251270.KS", nameKo: "넷마블", nameEn: "Netmarble" },
  { symbol: "271560.KS", nameKo: "오리온", nameEn: "Orion" },
  { symbol: "298040.KS", nameKo: "효성중공업", nameEn: "Hyosung Heavy Industries" },
  { symbol: "307950.KS", nameKo: "현대오토에버", nameEn: "Hyundai Autoever" },
  { symbol: "316140.KS", nameKo: "우리금융지주", nameEn: "Woori Financial Group" },
  { symbol: "000880.KS", nameKo: "한화", nameEn: "Hanwha" },
  { symbol: "326030.KS", nameKo: "SK바이오팜", nameEn: "SK Biopharmaceuticals" },
  { symbol: "352820.KS", nameKo: "하이브", nameEn: "HYBE" },
  { symbol: "302440.KS", nameKo: "SK바이오사이언스", nameEn: "SK Bioscience" },
  { symbol: "323410.KS", nameKo: "카카오뱅크", nameEn: "KakaoBank" },
  { symbol: "259960.KS", nameKo: "크래프톤", nameEn: "Krafton" },
  { symbol: "267250.KS", nameKo: "HD현대", nameEn: "HD Hyundai" },
  { symbol: "377300.KS", nameKo: "카카오페이", nameEn: "KakaoPay" },
  { symbol: "402340.KS", nameKo: "SK스퀘어", nameEn: "SK Square" },
  { symbol: "373220.KS", nameKo: "LG에너지솔루션", nameEn: "LG Energy Solution" },
  { symbol: "454910.KS", nameKo: "두산로보틱스", nameEn: "Doosan Robotics" },
  { symbol: "450080.KS", nameKo: "에코프로머티", nameEn: "EcoPro Materials" },
  { symbol: "278470.KS", nameKo: "에이피알", nameEn: "APR" },
  { symbol: "443060.KS", nameKo: "HD현대마린솔루션", nameEn: "HD Hyundai Marine Solution" },
  { symbol: "018880.KS", nameKo: "한온시스템", nameEn: "Hanon Systems" },
  { symbol: "011780.KS", nameKo: "금호석유화학", nameEn: "Kumho Petrochemical" },
  { symbol: "069620.KS", nameKo: "대웅제약", nameEn: "Daewoong Pharmaceutical" },
  { symbol: "030000.KS", nameKo: "제일기획", nameEn: "Cheil Worldwide" },
  { symbol: "306200.KS", nameKo: "세아제강", nameEn: "SeAH Steel" },
  { symbol: "004000.KS", nameKo: "롯데정밀화학", nameEn: "Lotte Fine Chemical" },
  { symbol: "001440.KS", nameKo: "대한전선", nameEn: "Taihan Electric Wire" },
  { symbol: "069960.KS", nameKo: "현대백화점", nameEn: "Hyundai Department Store" },
  { symbol: "097950.KS", nameKo: "CJ제일제당", nameEn: "CJ CheilJedang" },
  { symbol: "000120.KS", nameKo: "CJ대한통운", nameEn: "CJ Logistics" },
  { symbol: "023530.KS", nameKo: "롯데쇼핑", nameEn: "Lotte Shopping" },
  { symbol: "005300.KS", nameKo: "롯데칠성음료", nameEn: "Lotte Chilsung Beverage" },
  { symbol: "082740.KS", nameKo: "한화엔진", nameEn: "Hanwha Engine" },
  { symbol: "028670.KS", nameKo: "팬오션", nameEn: "Pan Ocean" },
  { symbol: "138930.KS", nameKo: "BNK금융지주", nameEn: "BNK Financial Group" },
  { symbol: "017800.KS", nameKo: "현대엘리베이터", nameEn: "Hyundai Elevator" },
  { symbol: "000990.KS", nameKo: "DB하이텍", nameEn: "DB HiTek" },
  { symbol: "003240.KS", nameKo: "태광산업", nameEn: "Taekwang Industrial" },
  { symbol: "002790.KS", nameKo: "아모레퍼시픽홀딩스", nameEn: "AmorePacific Group" },
  { symbol: "007340.KS", nameKo: "DN오토모티브", nameEn: "DN Automotive" },
  { symbol: "088350.KS", nameKo: "한화생명", nameEn: "Hanwha Life Insurance" },
  { symbol: "011210.KS", nameKo: "현대위아", nameEn: "Hyundai Wia" },
  { symbol: "000210.KS", nameKo: "DL", nameEn: "DL Holdings" },
  { symbol: "000080.KS", nameKo: "하이트진로", nameEn: "Hite Jinro" },
  { symbol: "073240.KS", nameKo: "금호타이어", nameEn: "Kumho Tire" },
  { symbol: "010060.KS", nameKo: "OCI홀딩스", nameEn: "OCI Holdings" },
  { symbol: "000670.KS", nameKo: "영풍", nameEn: "Youngpoong" },
  { symbol: "103140.KS", nameKo: "풍산", nameEn: "Poongsan" },
  { symbol: "004170.KS", nameKo: "신세계", nameEn: "Shinsegae" },
  { symbol: "120110.KS", nameKo: "코오롱인더", nameEn: "Kolon Industries" },
  { symbol: "052690.KS", nameKo: "한전기술", nameEn: "KEPCO Engineering & Construction" },
  { symbol: "004370.KS", nameKo: "농심", nameEn: "Nongshim" },
  { symbol: "012750.KS", nameKo: "에스원", nameEn: "S-1 Corporation" },
  { symbol: "001680.KS", nameKo: "대상", nameEn: "Daesang" },
  { symbol: "069260.KS", nameKo: "TKG휴켐스", nameEn: "TKG Huchems" },
  { symbol: "006260.KS", nameKo: "LS", nameEn: "LS Corp" },
  { symbol: "005850.KS", nameKo: "에스엘", nameEn: "SL Corporation" },
  { symbol: "007310.KS", nameKo: "오뚜기", nameEn: "Ottogi" },
  { symbol: "047040.KS", nameKo: "대우건설", nameEn: "Daewoo Engineering & Construction" },
  { symbol: "002380.KS", nameKo: "KCC", nameEn: "KCC Corporation" },
  { symbol: "001450.KS", nameKo: "현대해상", nameEn: "Hyundai Marine & Fire Insurance" },
  { symbol: "007070.KS", nameKo: "GS리테일", nameEn: "GS Retail" },
  { symbol: "007660.KS", nameKo: "이수페타시스", nameEn: "Isu Petasys" },
  { symbol: "008770.KS", nameKo: "호텔신라", nameEn: "Hotel Shilla" },
  { symbol: "008930.KS", nameKo: "한미사이언스", nameEn: "Hanmi Science" },
  { symbol: "009240.KS", nameKo: "한샘", nameEn: "Hanssem" },
  { symbol: "009970.KS", nameKo: "영원무역홀딩스", nameEn: "Youngone Holdings" },
  { symbol: "014680.KS", nameKo: "한솔케미칼", nameEn: "Hansol Chemical" },
  { symbol: "014820.KS", nameKo: "동원시스템즈", nameEn: "Dongwon Systems" },
  { symbol: "051600.KS", nameKo: "한전KPS", nameEn: "KEPCO Plant Service & Engineering" },
  { symbol: "071320.KS", nameKo: "지역난방공사", nameEn: "Korea District Heating Corp" },
  { symbol: "111770.KS", nameKo: "영원무역", nameEn: "Youngone Corporation" },
  { symbol: "139130.KS", nameKo: "iM금융지주", nameEn: "iM Financial Group" },
  { symbol: "139480.KS", nameKo: "이마트", nameEn: "E-Mart" },
  { symbol: "161890.KS", nameKo: "한국콜마", nameEn: "Korea Kolmar" },
  { symbol: "175330.KS", nameKo: "JB금융지주", nameEn: "JB Financial Group" },
  { symbol: "185750.KS", nameKo: "종근당", nameEn: "Chong Kun Dang Pharmaceutical" },
  { symbol: "192820.KS", nameKo: "코스맥스", nameEn: "Cosmax" },
  { symbol: "204320.KS", nameKo: "HL만도", nameEn: "HL Mando" },
  { symbol: "026960.KS", nameKo: "동서", nameEn: "Dongsuh Companies" },
  { symbol: "034230.KS", nameKo: "파라다이스", nameEn: "Paradise" },
  { symbol: "066970.KS", nameKo: "엘앤에프", nameEn: "L&F" },
  { symbol: "192080.KS", nameKo: "더블유게임즈", nameEn: "DoubleU Games" },
  { symbol: "282330.KS", nameKo: "BGF리테일", nameEn: "BGF Retail" },
  { symbol: "285130.KS", nameKo: "SK케미칼", nameEn: "SK Chemicals" },
  { symbol: "298020.KS", nameKo: "효성티앤씨", nameEn: "Hyosung TNC" },
  { symbol: "298050.KS", nameKo: "HS효성첨단소재", nameEn: "HS Hyosung Advanced Materials" },
  { symbol: "280360.KS", nameKo: "롯데웰푸드", nameEn: "Lotte Wellfood" },
  { symbol: "300720.KS", nameKo: "한일시멘트", nameEn: "Hanil Cement" },
  { symbol: "375500.KS", nameKo: "DL이앤씨", nameEn: "DL E&C" },
  { symbol: "361610.KS", nameKo: "SK아이이테크놀로지", nameEn: "SK IE Technology" },
  { symbol: "137310.KS", nameKo: "에스디바이오센서", nameEn: "SD Biosensor" },
  { symbol: "383220.KS", nameKo: "F&F", nameEn: "F&F" },
  { symbol: "062040.KS", nameKo: "산일전기", nameEn: "Sanil Electric" },
  { symbol: "002030.KS", nameKo: "아세아", nameEn: "Asia Holdings" },
  { symbol: "183190.KS", nameKo: "아세아시멘트", nameEn: "Asia Cement" },
  { symbol: "267270.KS", nameKo: "HD건설기계", nameEn: "HD Hyundai Construction Equipment" },
  { symbol: "006280.KS", nameKo: "녹십자", nameEn: "GC Biopharma" },
  { symbol: "005420.KS", nameKo: "코스모화학", nameEn: "Cosmo Chemical" },
  { symbol: "006040.KS", nameKo: "동원산업", nameEn: "Dongwon Industries" },
  { symbol: "457190.KS", nameKo: "이수스페셜티케미컬", nameEn: "Isu Specialty Chemical" },
  { symbol: "009420.KS", nameKo: "한올바이오파마", nameEn: "Hanall Biopharma" },
  { symbol: "064400.KS", nameKo: "LG씨엔에스", nameEn: "LG CNS" },
  { symbol: "214320.KS", nameKo: "이노션", nameEn: "Innocean Worldwide" },
  { symbol: "000240.KS", nameKo: "한국앤컴퍼니", nameEn: "Hankook & Company" },
  { symbol: "004990.KS", nameKo: "롯데지주", nameEn: "Lotte Corporation" },
  { symbol: "020000.KS", nameKo: "한섬", nameEn: "Handsome Corporation" },
  { symbol: "020560.KS", nameKo: "아시아나항공", nameEn: "Asiana Airlines" },
  { symbol: "031210.KS", nameKo: "서울보증보험", nameEn: "Seoul Guarantee Insurance" },
  { symbol: "105630.KS", nameKo: "한세실업", nameEn: "Hansae" },
]
