import type { Stock } from "@/types/stock"

export const KOSPI100_STOCKS: Stock[] = [
  { symbol: "005930.KS", nameKo: "삼성전자", nameEn: "Samsung Electronics" },
  { symbol: "000660.KS", nameKo: "SK하이닉스", nameEn: "SK Hynix" },
  { symbol: "066570.KS", nameKo: "LG전자", nameEn: "LG Electronics" },
  { symbol: "009150.KS", nameKo: "삼성전기", nameEn: "Samsung Electro-Mechanics" },
  { symbol: "012450.KS", nameKo: "한화에어로스페이스", nameEn: "Hanwha Aerospace" },
  { symbol: "011200.KS", nameKo: "HMM", nameEn: "HMM" },
  { symbol: "010140.KS", nameKo: "삼성중공업", nameEn: "Samsung Heavy Industries" },
  { symbol: "000810.KS", nameKo: "삼성화재해상보험", nameEn: "Samsung Fire & Marine Insurance" },
  { symbol: "000720.KS", nameKo: "현대건설", nameEn: "Hyundai Engineering & Construction" },
  { symbol: "011170.KS", nameKo: "롯데케미칼", nameEn: "Lotte Chemical" },
  { symbol: "086790.KS", nameKo: "하나금융지주", nameEn: "Hana Financial Group" },
  { symbol: "086280.KS", nameKo: "현대글로비스", nameEn: "Hyundai Glovis" },
  { symbol: "010130.KS", nameKo: "고려아연", nameEn: "Korea Zinc" },
  { symbol: "012330.KS", nameKo: "현대모비스", nameEn: "Hyundai Mobis" },
  { symbol: "005380.KS", nameKo: "현대차", nameEn: "Hyundai Motor" },
  { symbol: "004020.KS", nameKo: "현대제철", nameEn: "Hyundai Steel" },
  { symbol: "096770.KS", nameKo: "SK이노베이션", nameEn: "SK Innovation" },
  { symbol: "016360.KS", nameKo: "삼성증권", nameEn: "Samsung Securities" },
  { symbol: "105560.KS", nameKo: "KB금융", nameEn: "KB Financial Group" },
  { symbol: "090430.KS", nameKo: "아모레퍼시픽", nameEn: "Amorepacific" },
  { symbol: "035250.KS", nameKo: "강원랜드", nameEn: "Kangwon Land" },
  { symbol: "051910.KS", nameKo: "LG화학", nameEn: "LG Chem" },
  { symbol: "029780.KS", nameKo: "삼성카드", nameEn: "Samsung Card" },
  { symbol: "032830.KS", nameKo: "삼성생명", nameEn: "Samsung Life Insurance" },
  { symbol: "028050.KS", nameKo: "삼성엔지니어링", nameEn: "Samsung Engineering" },
  { symbol: "042660.KS", nameKo: "한화오션", nameEn: "Hanwha Ocean" },
  { symbol: "128940.KS", nameKo: "한미약품", nameEn: "Hanmi Pharm" },
  { symbol: "006800.KS", nameKo: "미래에셋증권", nameEn: "Mirae Asset Securities" },
  { symbol: "036570.KS", nameKo: "엔씨소프트", nameEn: "NCsoft" },
  { symbol: "006400.KS", nameKo: "삼성SDI", nameEn: "Samsung SDI" },
  { symbol: "055550.KS", nameKo: "신한지주", nameEn: "Shinhan Financial Group" },
  { symbol: "005830.KS", nameKo: "DB손해보험", nameEn: "DB Insurance" },
  { symbol: "009830.KS", nameKo: "한화솔루션", nameEn: "Hanwha Solutions" },
  { symbol: "000270.KS", nameKo: "기아", nameEn: "Kia" },
  { symbol: "034220.KS", nameKo: "LG디스플레이", nameEn: "LG Display" },
  { symbol: "011070.KS", nameKo: "LG이노텍", nameEn: "LG Innotek" },
  { symbol: "017670.KS", nameKo: "SK텔레콤", nameEn: "SK Telecom" },
  { symbol: "010950.KS", nameKo: "S-Oil", nameEn: "S-Oil" },
  { symbol: "010120.KS", nameKo: "LS ELECTRIC", nameEn: "LS Electric" },
  { symbol: "028260.KS", nameKo: "삼성물산", nameEn: "Samsung C&T" },
  { symbol: "033780.KS", nameKo: "KT&G", nameEn: "KT&G" },
  { symbol: "032640.KS", nameKo: "LG유플러스", nameEn: "LG Uplus" },
  { symbol: "035420.KS", nameKo: "NAVER", nameEn: "Naver" },
  { symbol: "078930.KS", nameKo: "GS", nameEn: "GS Holdings" },
  { symbol: "030200.KS", nameKo: "KT", nameEn: "KT Corporation" },
  { symbol: "003550.KS", nameKo: "LG", nameEn: "LG Corp" },
  { symbol: "003490.KS", nameKo: "대한항공", nameEn: "Korean Air Lines" },
  { symbol: "000150.KS", nameKo: "두산", nameEn: "Doosan" },
  { symbol: "034730.KS", nameKo: "SK", nameEn: "SK Holdings" },
  { symbol: "051900.KS", nameKo: "LG생활건강", nameEn: "LG Household & Health Care" },
  { symbol: "021240.KS", nameKo: "코웨이", nameEn: "Coway" },
  { symbol: "015760.KS", nameKo: "한국전력공사", nameEn: "Korea Electric Power (KEPCO)" },
  { symbol: "036460.KS", nameKo: "한국가스공사", nameEn: "Korea Gas Corporation" },
  { symbol: "005490.KS", nameKo: "POSCO홀딩스", nameEn: "POSCO Holdings" },
  { symbol: "000100.KS", nameKo: "유한양행", nameEn: "Yuhan Corporation" },
  { symbol: "047050.KS", nameKo: "포스코인터내셔널", nameEn: "POSCO International" },
  { symbol: "011790.KS", nameKo: "SKC", nameEn: "SKC" },
  { symbol: "071050.KS", nameKo: "한국금융지주", nameEn: "Korea Investment Holdings" },
  { symbol: "009540.KS", nameKo: "HD한국조선해양", nameEn: "HD Korea Shipbuilding & Offshore Engineering" },
  { symbol: "024110.KS", nameKo: "기업은행", nameEn: "Industrial Bank of Korea" },
  { symbol: "034020.KS", nameKo: "두산에너빌리티", nameEn: "Doosan Enerbility" },
  { symbol: "005940.KS", nameKo: "NH투자증권", nameEn: "NH Investment & Securities" },
  { symbol: "003230.KS", nameKo: "삼양식품", nameEn: "Samyang Foods" },
  { symbol: "039490.KS", nameKo: "키움증권", nameEn: "Kiwoom Securities" },
  { symbol: "042700.KS", nameKo: "한미반도체", nameEn: "Hanmi Semiconductor" },
  { symbol: "047810.KS", nameKo: "한국항공우주산업", nameEn: "Korea Aerospace Industries" },
  { symbol: "138040.KS", nameKo: "메리츠금융지주", nameEn: "Meritz Financial Group" },
  { symbol: "161390.KS", nameKo: "한국타이어앤테크놀로지", nameEn: "Hankook Tire & Technology" },
  { symbol: "180640.KS", nameKo: "한진칼", nameEn: "Hanjin Kal" },
  { symbol: "064350.KS", nameKo: "현대로템", nameEn: "Hyundai Rotem" },
  { symbol: "018260.KS", nameKo: "삼성에스디에스", nameEn: "Samsung SDS" },
  { symbol: "079550.KS", nameKo: "LIG넥스원", nameEn: "LIG Nex1" },
  { symbol: "003670.KS", nameKo: "포스코퓨처엠", nameEn: "POSCO Future M" },
  { symbol: "022100.KS", nameKo: "포스코DX", nameEn: "POSCO DX" },
  { symbol: "035720.KS", nameKo: "카카오", nameEn: "Kakao" },
  { symbol: "068270.KS", nameKo: "셀트리온", nameEn: "Celltrion" },
  { symbol: "207940.KS", nameKo: "삼성바이오로직스", nameEn: "Samsung Biologics" },
  { symbol: "241560.KS", nameKo: "두산밥캣", nameEn: "Doosan Bobcat" },
  { symbol: "329180.KS", nameKo: "HD현대중공업", nameEn: "HD Hyundai Heavy Industries" },
  { symbol: "267260.KS", nameKo: "HD현대일렉트릭", nameEn: "HD Hyundai Electric" },
  { symbol: "251270.KS", nameKo: "넷마블", nameEn: "Netmarble" },
  { symbol: "271560.KS", nameKo: "오리온", nameEn: "Orion" },
  { symbol: "298040.KS", nameKo: "효성중공업", nameEn: "Hyosung Heavy Industries" },
  { symbol: "307950.KS", nameKo: "현대오토에버", nameEn: "Hyundai Autoever" },
  { symbol: "316140.KS", nameKo: "우리금융지주", nameEn: "Woori Financial Group" },
  { symbol: "000880.KS", nameKo: "한화", nameEn: "Hanwha" },
  { symbol: "326030.KS", nameKo: "SK바이오팜", nameEn: "SK Biopharmaceuticals" },
  { symbol: "352820.KS", nameKo: "하이브", nameEn: "HYBE" },
  { symbol: "302440.KS", nameKo: "SK바이오사이언스", nameEn: "SK Bioscience" },
  { symbol: "323410.KS", nameKo: "카카오뱅크", nameEn: "KakaoBank" },
  { symbol: "259960.KS", nameKo: "크래프톤", nameEn: "Krafton" },
  { symbol: "267250.KS", nameKo: "HD현대", nameEn: "HD Hyundai" },
  { symbol: "377300.KS", nameKo: "카카오페이", nameEn: "KakaoPay" },
  { symbol: "402340.KS", nameKo: "SK스퀘어", nameEn: "SK Square" },
  { symbol: "373220.KS", nameKo: "LG에너지솔루션", nameEn: "LG Energy Solution" },
  { symbol: "454910.KS", nameKo: "두산로보틱스", nameEn: "Doosan Robotics" },
  { symbol: "450080.KS", nameKo: "에코프로머티", nameEn: "EcoPro Materials" },
  { symbol: "278470.KS", nameKo: "에이피알", nameEn: "APR" },
  { symbol: "443060.KS", nameKo: "HD현대마린솔루션", nameEn: "HD Hyundai Marine Solution" },
]
