import type { Stock } from "@/types/stock"

export const SP500_STOCKS: Stock[] = [
  { symbol: "MMM", nameKo: "3M", nameEn: "3M" },
  { symbol: "AOS", nameKo: "A. O. Smith", nameEn: "A. O. Smith" },
  { symbol: "ABT", nameKo: "애보트 래보라토리스", nameEn: "Abbott Laboratories" },
  { symbol: "ABBV", nameKo: "애브비", nameEn: "AbbVie" },
  { symbol: "ACN", nameKo: "액센츄어", nameEn: "Accenture" },
  { symbol: "ADBE", nameKo: "어도비", nameEn: "Adobe" },
  { symbol: "AMD", nameKo: "AMD", nameEn: "Advanced Micro Devices" },
  { symbol: "AES", nameKo: "AES", nameEn: "AES" },
  { symbol: "AFL", nameKo: "아플락", nameEn: "Aflac" },
  { symbol: "A", nameKo: "애질런트 테크놀로지스", nameEn: "Agilent Technologies" },
  { symbol: "APD", nameKo: "에어 프로덕츠", nameEn: "Air Products" },
  { symbol: "ABNB", nameKo: "에어비앤비", nameEn: "Airbnb" },
  { symbol: "AKAM", nameKo: "Akamai Technologies", nameEn: "Akamai Technologies" },
  { symbol: "ALB", nameKo: "앨버말", nameEn: "Albemarle" },
  { symbol: "ARE", nameKo: "Alexandria Real Estate Equities", nameEn: "Alexandria Real Estate Equities" },
  { symbol: "ALGN", nameKo: "Align Technology", nameEn: "Align Technology" },
  { symbol: "ALLE", nameKo: "Allegion", nameEn: "Allegion" },
  { symbol: "LNT", nameKo: "Alliant Energy", nameEn: "Alliant Energy" },
  { symbol: "ALL", nameKo: "Allstate", nameEn: "Allstate" },
  { symbol: "GOOGL", nameKo: "알파벳(구글) A", nameEn: "Alphabet (Class A)" },
  { symbol: "GOOG", nameKo: "알파벳(구글) C", nameEn: "Alphabet (Class C)" },
  { symbol: "MO", nameKo: "알트리아 그룹", nameEn: "Altria" },
  { symbol: "AMZN", nameKo: "아마존", nameEn: "Amazon" },
  { symbol: "AMCR", nameKo: "Amcor", nameEn: "Amcor" },
  { symbol: "AEE", nameKo: "Ameren", nameEn: "Ameren" },
  { symbol: "AEP", nameKo: "American Electric Power", nameEn: "American Electric Power" },
  { symbol: "AXP", nameKo: "아메리칸 익스프레스", nameEn: "American Express" },
  { symbol: "AIG", nameKo: "AIG", nameEn: "American International Group" },
  { symbol: "AMT", nameKo: "아메리칸 타워", nameEn: "American Tower" },
  { symbol: "AWK", nameKo: "American Water Works", nameEn: "American Water Works" },
  { symbol: "AMP", nameKo: "Ameriprise Financial", nameEn: "Ameriprise Financial" },
  { symbol: "AME", nameKo: "Ametek", nameEn: "Ametek" },
  { symbol: "AMGN", nameKo: "암젠", nameEn: "Amgen" },
  { symbol: "APH", nameKo: "Amphenol", nameEn: "Amphenol" },
  { symbol: "ADI", nameKo: "아날로그 디바이스", nameEn: "Analog Devices" },
  { symbol: "AON", nameKo: "에이온", nameEn: "Aon" },
  { symbol: "APA", nameKo: "APA", nameEn: "APA" },
  { symbol: "APO", nameKo: "Apollo Global Management", nameEn: "Apollo Global Management" },
  { symbol: "AAPL", nameKo: "애플", nameEn: "Apple" },
  { symbol: "AMAT", nameKo: "어플라이드 머티어리얼즈", nameEn: "Applied Materials" },
  { symbol: "APP", nameKo: "AppLovin", nameEn: "AppLovin" },
  { symbol: "APTV", nameKo: "앱티브", nameEn: "Aptiv" },
  { symbol: "ACGL", nameKo: "Arch Capital Group", nameEn: "Arch Capital Group" },
  { symbol: "ADM", nameKo: "아처 다니엘스 미들랜드", nameEn: "Archer Daniels Midland" },
  { symbol: "ARES", nameKo: "Ares Management", nameEn: "Ares Management" },
  { symbol: "ANET", nameKo: "아리스타 네트웍스", nameEn: "Arista Networks" },
  { symbol: "AJG", nameKo: "Arthur J. Gallagher", nameEn: "Arthur J. Gallagher" },
  { symbol: "AIZ", nameKo: "Assurant", nameEn: "Assurant" },
  { symbol: "T", nameKo: "AT&T", nameEn: "AT&T" },
  { symbol: "ATO", nameKo: "Atmos Energy", nameEn: "Atmos Energy" },
  { symbol: "ADSK", nameKo: "오토데스크", nameEn: "Autodesk" },
  { symbol: "ADP", nameKo: "오토매틱 데이터 프로세싱", nameEn: "Automatic Data Processing" },
  { symbol: "AZO", nameKo: "오토존", nameEn: "AutoZone" },
  { symbol: "AVB", nameKo: "AvalonBay Communities", nameEn: "AvalonBay Communities" },
  { symbol: "AVY", nameKo: "Avery Dennison", nameEn: "Avery Dennison" },
  { symbol: "AXON", nameKo: "Axon Enterprise", nameEn: "Axon Enterprise" },
  { symbol: "BKR", nameKo: "베이커 휴즈", nameEn: "Baker Hughes" },
  { symbol: "BALL", nameKo: "Ball", nameEn: "Ball" },
  { symbol: "BAC", nameKo: "뱅크오브아메리카", nameEn: "Bank of America" },
  { symbol: "BAX", nameKo: "백스터 인터내셔널", nameEn: "Baxter International" },
  { symbol: "BDX", nameKo: "벡톤 디킨슨", nameEn: "Becton Dickinson" },
  { symbol: "BRK-B", nameKo: "버크셔 해서웨이", nameEn: "Berkshire Hathaway" },
  { symbol: "BBY", nameKo: "베스트바이", nameEn: "Best Buy" },
  { symbol: "TECH", nameKo: "Bio-Techne", nameEn: "Bio-Techne" },
  { symbol: "BIIB", nameKo: "바이오젠", nameEn: "Biogen" },
  { symbol: "BLK", nameKo: "블랙록", nameEn: "BlackRock" },
  { symbol: "BX", nameKo: "블랙스톤", nameEn: "Blackstone" },
  { symbol: "XYZ", nameKo: "Block", nameEn: "Block" },
  { symbol: "BNY", nameKo: "BNY Mellon", nameEn: "BNY Mellon" },
  { symbol: "BA", nameKo: "보잉", nameEn: "Boeing" },
  { symbol: "BKNG", nameKo: "부킹홀딩스", nameEn: "Booking Holdings" },
  { symbol: "BSX", nameKo: "보스턴 사이언티픽", nameEn: "Boston Scientific" },
  { symbol: "BMY", nameKo: "브리스톨 마이어스 스큅", nameEn: "Bristol Myers Squibb" },
  { symbol: "AVGO", nameKo: "브로드컴", nameEn: "Broadcom" },
  { symbol: "BR", nameKo: "Broadridge Financial Solutions", nameEn: "Broadridge Financial Solutions" },
  { symbol: "BRO", nameKo: "Brown & Brown", nameEn: "Brown & Brown" },
  { symbol: "BF-B", nameKo: "Brown–Forman", nameEn: "Brown–Forman" },
  { symbol: "BLDR", nameKo: "Builders FirstSource", nameEn: "Builders FirstSource" },
  { symbol: "BG", nameKo: "Bunge Global", nameEn: "Bunge Global" },
  { symbol: "BXP", nameKo: "BXP", nameEn: "BXP" },
  { symbol: "CHRW", nameKo: "C.H. Robinson", nameEn: "C.H. Robinson" },
  { symbol: "CDNS", nameKo: "케이던스 디자인 시스템즈", nameEn: "Cadence Design Systems" },
  { symbol: "CPT", nameKo: "Camden Property Trust", nameEn: "Camden Property Trust" },
  { symbol: "COF", nameKo: "캐피털 원", nameEn: "Capital One" },
  { symbol: "CAH", nameKo: "카디널 헬스", nameEn: "Cardinal Health" },
  { symbol: "CCL", nameKo: "카니발 코퍼레이션", nameEn: "Carnival" },
  { symbol: "CARR", nameKo: "Carrier Global", nameEn: "Carrier Global" },
  { symbol: "CVNA", nameKo: "Carvana", nameEn: "Carvana" },
  { symbol: "CASY", nameKo: "Casey's", nameEn: "Casey's" },
  { symbol: "CAT", nameKo: "캐터필러", nameEn: "Caterpillar" },
  { symbol: "CBOE", nameKo: "Cboe Global Markets", nameEn: "Cboe Global Markets" },
  { symbol: "CBRE", nameKo: "CBRE 그룹", nameEn: "CBRE Group" },
  { symbol: "CDW", nameKo: "CDW", nameEn: "CDW" },
  { symbol: "COR", nameKo: "Cencora", nameEn: "Cencora" },
  { symbol: "CNC", nameKo: "Centene", nameEn: "Centene" },
  { symbol: "CNP", nameKo: "CenterPoint Energy", nameEn: "CenterPoint Energy" },
  { symbol: "CF", nameKo: "CF Industries", nameEn: "CF Industries" },
  { symbol: "CRL", nameKo: "Charles River Laboratories", nameEn: "Charles River Laboratories" },
  { symbol: "SCHW", nameKo: "찰스 슈왑", nameEn: "Charles Schwab" },
  { symbol: "CHTR", nameKo: "차터 커뮤니케이션즈", nameEn: "Charter Communications" },
  { symbol: "CVX", nameKo: "셰브론", nameEn: "Chevron" },
  { symbol: "CMG", nameKo: "치폴레 멕시칸 그릴", nameEn: "Chipotle Mexican Grill" },
  { symbol: "CB", nameKo: "처브", nameEn: "Chubb" },
  { symbol: "CHD", nameKo: "Church & Dwight", nameEn: "Church & Dwight" },
  { symbol: "CIEN", nameKo: "Ciena", nameEn: "Ciena" },
  { symbol: "CI", nameKo: "시그나", nameEn: "Cigna" },
  { symbol: "CINF", nameKo: "Cincinnati Financial", nameEn: "Cincinnati Financial" },
  { symbol: "CTAS", nameKo: "신타스", nameEn: "Cintas" },
  { symbol: "CSCO", nameKo: "시스코", nameEn: "Cisco" },
  { symbol: "C", nameKo: "씨티그룹", nameEn: "Citigroup" },
  { symbol: "CFG", nameKo: "Citizens Financial Group", nameEn: "Citizens Financial Group" },
  { symbol: "CLX", nameKo: "클로록스", nameEn: "Clorox" },
  { symbol: "CME", nameKo: "CME 그룹", nameEn: "CME Group" },
  { symbol: "CMS", nameKo: "CMS Energy", nameEn: "CMS Energy" },
  { symbol: "KO", nameKo: "코카콜라", nameEn: "Coca-Cola" },
  { symbol: "CTSH", nameKo: "코그니전트", nameEn: "Cognizant" },
  { symbol: "COHR", nameKo: "Coherent", nameEn: "Coherent" },
  { symbol: "COIN", nameKo: "코인베이스", nameEn: "Coinbase" },
  { symbol: "CL", nameKo: "콜게이트-파몰리브", nameEn: "Colgate-Palmolive" },
  { symbol: "CMCSA", nameKo: "컴캐스트", nameEn: "Comcast" },
  { symbol: "FIX", nameKo: "Comfort Systems USA", nameEn: "Comfort Systems USA" },
  { symbol: "COP", nameKo: "코노코필립스", nameEn: "ConocoPhillips" },
  { symbol: "ED", nameKo: "콘솔리데이티드 에디슨", nameEn: "Consolidated Edison" },
  { symbol: "STZ", nameKo: "Constellation Brands", nameEn: "Constellation Brands" },
  { symbol: "CEG", nameKo: "Constellation Energy", nameEn: "Constellation Energy" },
  { symbol: "COO", nameKo: "Cooper Companies", nameEn: "Cooper Companies" },
  { symbol: "CPRT", nameKo: "Copart", nameEn: "Copart" },
  { symbol: "GLW", nameKo: "Corning", nameEn: "Corning" },
  { symbol: "CPAY", nameKo: "Corpay", nameEn: "Corpay" },
  { symbol: "CTVA", nameKo: "Corteva", nameEn: "Corteva" },
  { symbol: "CSGP", nameKo: "CoStar Group", nameEn: "CoStar Group" },
  { symbol: "COST", nameKo: "코스트코", nameEn: "Costco" },
  { symbol: "CRH", nameKo: "CRH", nameEn: "CRH" },
  { symbol: "CRWD", nameKo: "크라우드스트라이크", nameEn: "CrowdStrike" },
  { symbol: "CCI", nameKo: "크라운 캐슬", nameEn: "Crown Castle" },
  { symbol: "CSX", nameKo: "CSX", nameEn: "CSX" },
  { symbol: "CMI", nameKo: "커민스", nameEn: "Cummins" },
  { symbol: "CVS", nameKo: "CVS 헬스", nameEn: "CVS Health" },
  { symbol: "DHR", nameKo: "다나허", nameEn: "Danaher" },
  { symbol: "DRI", nameKo: "Darden Restaurants", nameEn: "Darden Restaurants" },
  { symbol: "DDOG", nameKo: "Datadog", nameEn: "Datadog" },
  { symbol: "DVA", nameKo: "DaVita", nameEn: "DaVita" },
  { symbol: "DECK", nameKo: "Deckers Brands", nameEn: "Deckers Brands" },
  { symbol: "DE", nameKo: "디어", nameEn: "Deere" },
  { symbol: "DELL", nameKo: "델 테크놀로지스", nameEn: "Dell Technologies" },
  { symbol: "DAL", nameKo: "델타 항공", nameEn: "Delta Air Lines" },
  { symbol: "DVN", nameKo: "Devon Energy", nameEn: "Devon Energy" },
  { symbol: "DXCM", nameKo: "Dexcom", nameEn: "Dexcom" },
  { symbol: "FANG", nameKo: "Diamondback Energy", nameEn: "Diamondback Energy" },
  { symbol: "DLR", nameKo: "Digital Realty", nameEn: "Digital Realty" },
  { symbol: "DG", nameKo: "달러 제너럴", nameEn: "Dollar General" },
  { symbol: "DLTR", nameKo: "달러 트리", nameEn: "Dollar Tree" },
  { symbol: "D", nameKo: "도미니언 에너지", nameEn: "Dominion Energy" },
  { symbol: "DPZ", nameKo: "도미노피자", nameEn: "Domino's" },
  { symbol: "DASH", nameKo: "도어대시", nameEn: "DoorDash" },
  { symbol: "DOV", nameKo: "Dover", nameEn: "Dover" },
  { symbol: "DOW", nameKo: "다우", nameEn: "Dow" },
  { symbol: "DHI", nameKo: "D.R. 호턴", nameEn: "D. R. Horton" },
  { symbol: "DTE", nameKo: "DTE Energy", nameEn: "DTE Energy" },
  { symbol: "DUK", nameKo: "듀크 에너지", nameEn: "Duke Energy" },
  { symbol: "DD", nameKo: "듀폰", nameEn: "DuPont" },
  { symbol: "ETN", nameKo: "Eaton", nameEn: "Eaton" },
  { symbol: "EBAY", nameKo: "이베이", nameEn: "eBay" },
  { symbol: "ECHO", nameKo: "EchoStar", nameEn: "EchoStar" },
  { symbol: "ECL", nameKo: "에코랩", nameEn: "Ecolab" },
  { symbol: "EIX", nameKo: "Edison International", nameEn: "Edison International" },
  { symbol: "EW", nameKo: "Edwards Lifesciences", nameEn: "Edwards Lifesciences" },
  { symbol: "EA", nameKo: "일렉트로닉 아츠", nameEn: "Electronic Arts" },
  { symbol: "ELV", nameKo: "Elevance Health", nameEn: "Elevance Health" },
  { symbol: "EME", nameKo: "Emcor", nameEn: "Emcor" },
  { symbol: "EMR", nameKo: "Emerson Electric", nameEn: "Emerson Electric" },
  { symbol: "ETR", nameKo: "Entergy", nameEn: "Entergy" },
  { symbol: "EOG", nameKo: "EOG 리소스", nameEn: "EOG Resources" },
  { symbol: "EQT", nameKo: "EQT", nameEn: "EQT" },
  { symbol: "EFX", nameKo: "에퀴팩스", nameEn: "Equifax" },
  { symbol: "EQIX", nameKo: "에퀴닉스", nameEn: "Equinix" },
  { symbol: "EQR", nameKo: "Equity Residential", nameEn: "Equity Residential" },
  { symbol: "ERIE", nameKo: "Erie Indemnity", nameEn: "Erie Indemnity" },
  { symbol: "ESS", nameKo: "Essex Property Trust", nameEn: "Essex Property Trust" },
  { symbol: "EL", nameKo: "에스티 로더", nameEn: "Estée Lauder Companies" },
  { symbol: "EG", nameKo: "Everest Group", nameEn: "Everest Group" },
  { symbol: "EVRG", nameKo: "Evergy", nameEn: "Evergy" },
  { symbol: "ES", nameKo: "Eversource Energy", nameEn: "Eversource Energy" },
  { symbol: "EXC", nameKo: "엑셀론", nameEn: "Exelon" },
  { symbol: "EXE", nameKo: "Expand Energy", nameEn: "Expand Energy" },
  { symbol: "EXPE", nameKo: "익스피디아 그룹", nameEn: "Expedia Group" },
  { symbol: "EXPD", nameKo: "Expeditors International", nameEn: "Expeditors International" },
  { symbol: "EXR", nameKo: "Extra Space Storage", nameEn: "Extra Space Storage" },
  { symbol: "XOM", nameKo: "엑슨모빌", nameEn: "ExxonMobil" },
  { symbol: "FFIV", nameKo: "F5", nameEn: "F5" },
  { symbol: "FDS", nameKo: "FactSet", nameEn: "FactSet" },
  { symbol: "FICO", nameKo: "Fair Isaac", nameEn: "Fair Isaac" },
  { symbol: "FAST", nameKo: "Fastenal", nameEn: "Fastenal" },
  { symbol: "FRT", nameKo: "Federal Realty Investment Trust", nameEn: "Federal Realty Investment Trust" },
  { symbol: "FDX", nameKo: "페덱스", nameEn: "FedEx" },
  { symbol: "FDXF", nameKo: "FedEx Freight", nameEn: "FedEx Freight" },
  { symbol: "FIS", nameKo: "Fidelity National Information Services", nameEn: "Fidelity National Information Services" },
  { symbol: "FITB", nameKo: "피프스 서드 뱅코프", nameEn: "Fifth Third Bancorp" },
  { symbol: "FSLR", nameKo: "First Solar", nameEn: "First Solar" },
  { symbol: "FE", nameKo: "퍼스트에너지", nameEn: "FirstEnergy" },
  { symbol: "FISV", nameKo: "Fiserv", nameEn: "Fiserv" },
  { symbol: "FLEX", nameKo: "Flex", nameEn: "Flex" },
  { symbol: "F", nameKo: "포드", nameEn: "Ford Motor" },
  { symbol: "FTNT", nameKo: "포티넷", nameEn: "Fortinet" },
  { symbol: "FTV", nameKo: "Fortive", nameEn: "Fortive" },
  { symbol: "FOXA", nameKo: "폭스 코퍼레이션 A", nameEn: "Fox (Class A)" },
  { symbol: "FOX", nameKo: "폭스 코퍼레이션 B", nameEn: "Fox (Class B)" },
  { symbol: "BEN", nameKo: "Franklin Resources", nameEn: "Franklin Resources" },
  { symbol: "FCX", nameKo: "프리포트-맥모란", nameEn: "Freeport-McMoRan" },
  { symbol: "GRMN", nameKo: "가민", nameEn: "Garmin" },
  { symbol: "IT", nameKo: "Gartner", nameEn: "Gartner" },
  { symbol: "GE", nameKo: "GE 에어로스페이스", nameEn: "GE Aerospace" },
  { symbol: "GEHC", nameKo: "GE HealthCare", nameEn: "GE HealthCare" },
  { symbol: "GEV", nameKo: "GE Vernova", nameEn: "GE Vernova" },
  { symbol: "GEN", nameKo: "Gen Digital", nameEn: "Gen Digital" },
  { symbol: "GNRC", nameKo: "Generac", nameEn: "Generac" },
  { symbol: "GD", nameKo: "제너럴 다이내믹스", nameEn: "General Dynamics" },
  { symbol: "GIS", nameKo: "제너럴 밀스", nameEn: "General Mills" },
  { symbol: "GM", nameKo: "제너럴 모터스", nameEn: "General Motors" },
  { symbol: "GPC", nameKo: "Genuine Parts", nameEn: "Genuine Parts" },
  { symbol: "GILD", nameKo: "길리어드 사이언스", nameEn: "Gilead Sciences" },
  { symbol: "GPN", nameKo: "Global Payments", nameEn: "Global Payments" },
  { symbol: "GL", nameKo: "Globe Life", nameEn: "Globe Life" },
  { symbol: "GDDY", nameKo: "GoDaddy", nameEn: "GoDaddy" },
  { symbol: "GS", nameKo: "골드만삭스", nameEn: "Goldman Sachs" },
  { symbol: "HAL", nameKo: "할리버튼", nameEn: "Halliburton" },
  { symbol: "HIG", nameKo: "Hartford", nameEn: "Hartford" },
  { symbol: "HAS", nameKo: "하스브로", nameEn: "Hasbro" },
  { symbol: "HCA", nameKo: "HCA 헬스케어", nameEn: "HCA Healthcare" },
  { symbol: "DOC", nameKo: "Healthpeak Properties", nameEn: "Healthpeak Properties" },
  { symbol: "HSIC", nameKo: "Henry Schein", nameEn: "Henry Schein" },
  { symbol: "HSY", nameKo: "허쉬", nameEn: "Hershey" },
  { symbol: "HPE", nameKo: "Hewlett Packard Enterprise", nameEn: "Hewlett Packard Enterprise" },
  { symbol: "HLT", nameKo: "힐튼 월드와이드", nameEn: "Hilton Worldwide" },
  { symbol: "HD", nameKo: "홈디포", nameEn: "Home Depot" },
  { symbol: "HONA", nameKo: "Honeywell Aerospace", nameEn: "Honeywell Aerospace" },
  { symbol: "HON", nameKo: "허니웰", nameEn: "Honeywell Technologies" },
  { symbol: "HRL", nameKo: "호멜 푸즈", nameEn: "Hormel Foods" },
  { symbol: "HST", nameKo: "Host Hotels & Resorts", nameEn: "Host Hotels & Resorts" },
  { symbol: "HWM", nameKo: "Howmet Aerospace", nameEn: "Howmet Aerospace" },
  { symbol: "HPQ", nameKo: "HP", nameEn: "HP" },
  { symbol: "HUBB", nameKo: "Hubbell", nameEn: "Hubbell" },
  { symbol: "HUM", nameKo: "휴마나", nameEn: "Humana" },
  { symbol: "HBAN", nameKo: "Huntington Bancshares", nameEn: "Huntington Bancshares" },
  { symbol: "HII", nameKo: "Huntington Ingalls Industries", nameEn: "Huntington Ingalls Industries" },
  { symbol: "IBM", nameKo: "IBM", nameEn: "IBM" },
  { symbol: "IEX", nameKo: "IDEX", nameEn: "IDEX" },
  { symbol: "IDXX", nameKo: "Idexx Laboratories", nameEn: "Idexx Laboratories" },
  { symbol: "ITW", nameKo: "일리노이 툴 웍스", nameEn: "Illinois Tool Works" },
  { symbol: "INCY", nameKo: "Incyte", nameEn: "Incyte" },
  { symbol: "IR", nameKo: "Ingersoll Rand", nameEn: "Ingersoll Rand" },
  { symbol: "PODD", nameKo: "Insulet", nameEn: "Insulet" },
  { symbol: "INTC", nameKo: "인텔", nameEn: "Intel" },
  { symbol: "IBKR", nameKo: "인터랙티브 브로커스", nameEn: "Interactive Brokers" },
  { symbol: "ICE", nameKo: "인터콘티넨탈 익스체인지", nameEn: "Intercontinental Exchange" },
  { symbol: "IFF", nameKo: "International Flavors & Fragrances", nameEn: "International Flavors & Fragrances" },
  { symbol: "IP", nameKo: "인터내셔널 페이퍼", nameEn: "International Paper" },
  { symbol: "INTU", nameKo: "인튜이트", nameEn: "Intuit" },
  { symbol: "ISRG", nameKo: "인튜이티브 서지컬", nameEn: "Intuitive Surgical" },
  { symbol: "IVZ", nameKo: "인베스코", nameEn: "Invesco" },
  { symbol: "INVH", nameKo: "Invitation Homes", nameEn: "Invitation Homes" },
  { symbol: "IQV", nameKo: "IQVIA", nameEn: "IQVIA" },
  { symbol: "IRM", nameKo: "Iron Mountain", nameEn: "Iron Mountain" },
  { symbol: "JBHT", nameKo: "J.B. 헌트", nameEn: "J.B. Hunt" },
  { symbol: "JBL", nameKo: "Jabil", nameEn: "Jabil" },
  { symbol: "JKHY", nameKo: "Jack Henry & Associates", nameEn: "Jack Henry & Associates" },
  { symbol: "J", nameKo: "Jacobs Solutions", nameEn: "Jacobs Solutions" },
  { symbol: "JNJ", nameKo: "존슨앤드존슨", nameEn: "Johnson & Johnson" },
  { symbol: "JCI", nameKo: "존슨 컨트롤즈", nameEn: "Johnson Controls" },
  { symbol: "JPM", nameKo: "JP모건", nameEn: "JPMorgan Chase" },
  { symbol: "KVUE", nameKo: "켄뷰", nameEn: "Kenvue" },
  { symbol: "KDP", nameKo: "큐리그 닥터페퍼", nameEn: "Keurig Dr Pepper" },
  { symbol: "KEY", nameKo: "키코프", nameEn: "KeyCorp" },
  { symbol: "KEYS", nameKo: "Keysight Technologies", nameEn: "Keysight Technologies" },
  { symbol: "KMB", nameKo: "킴벌리클라크", nameEn: "Kimberly-Clark" },
  { symbol: "KIM", nameKo: "Kimco Realty", nameEn: "Kimco Realty" },
  { symbol: "KMI", nameKo: "킨더 모건", nameEn: "Kinder Morgan" },
  { symbol: "KKR", nameKo: "KKR", nameEn: "KKR" },
  { symbol: "KLAC", nameKo: "KLA", nameEn: "KLA" },
  { symbol: "KHC", nameKo: "크래프트 하인즈", nameEn: "Kraft Heinz" },
  { symbol: "KR", nameKo: "크로거", nameEn: "Kroger" },
  { symbol: "LHX", nameKo: "L3Harris", nameEn: "L3Harris" },
  { symbol: "LH", nameKo: "랩콥", nameEn: "Labcorp" },
  { symbol: "LRCX", nameKo: "램 리서치", nameEn: "Lam Research" },
  { symbol: "LVS", nameKo: "라스베이거스 샌즈", nameEn: "Las Vegas Sands" },
  { symbol: "LDOS", nameKo: "Leidos", nameEn: "Leidos" },
  { symbol: "LEN", nameKo: "레나", nameEn: "Lennar" },
  { symbol: "LII", nameKo: "Lennox International", nameEn: "Lennox International" },
  { symbol: "LLY", nameKo: "일라이 릴리", nameEn: "Lilly (Eli)" },
  { symbol: "LIN", nameKo: "린데", nameEn: "Linde" },
  { symbol: "LYV", nameKo: "Live Nation Entertainment", nameEn: "Live Nation Entertainment" },
  { symbol: "LMT", nameKo: "록히드 마틴", nameEn: "Lockheed Martin" },
  { symbol: "L", nameKo: "Loews", nameEn: "Loews" },
  { symbol: "LOW", nameKo: "로우스", nameEn: "Lowe's" },
  { symbol: "LULU", nameKo: "룰루레몬", nameEn: "Lululemon Athletica" },
  { symbol: "LITE", nameKo: "Lumentum", nameEn: "Lumentum" },
  { symbol: "LYB", nameKo: "라이온델바젤", nameEn: "LyondellBasell" },
  { symbol: "MTB", nameKo: "M&T Bank", nameEn: "M&T Bank" },
  { symbol: "MPC", nameKo: "마라톤 페트롤리엄", nameEn: "Marathon Petroleum" },
  { symbol: "MAR", nameKo: "메리어트 인터내셔널", nameEn: "Marriott International" },
  { symbol: "MRSH", nameKo: "Marsh McLennan", nameEn: "Marsh McLennan" },
  { symbol: "MLM", nameKo: "Martin Marietta Materials", nameEn: "Martin Marietta Materials" },
  { symbol: "MRVL", nameKo: "Marvell Technology", nameEn: "Marvell Technology" },
  { symbol: "MAS", nameKo: "Masco", nameEn: "Masco" },
  { symbol: "MA", nameKo: "마스터카드", nameEn: "Mastercard" },
  { symbol: "MKC", nameKo: "McCormick", nameEn: "McCormick" },
  { symbol: "MCD", nameKo: "맥도날드", nameEn: "McDonald's" },
  { symbol: "MCK", nameKo: "맥케슨", nameEn: "McKesson" },
  { symbol: "MDT", nameKo: "메드트로닉", nameEn: "Medtronic" },
  { symbol: "MRK", nameKo: "머크", nameEn: "Merck" },
  { symbol: "META", nameKo: "메타", nameEn: "Meta Platforms" },
  { symbol: "MET", nameKo: "메트라이프", nameEn: "MetLife" },
  { symbol: "MTD", nameKo: "Mettler Toledo", nameEn: "Mettler Toledo" },
  { symbol: "MGM", nameKo: "MGM 리조트", nameEn: "MGM Resorts" },
  { symbol: "MCHP", nameKo: "Microchip Technology", nameEn: "Microchip Technology" },
  { symbol: "MU", nameKo: "마이크론 테크놀로지", nameEn: "Micron Technology" },
  { symbol: "MSFT", nameKo: "마이크로소프트", nameEn: "Microsoft" },
  { symbol: "MAA", nameKo: "Mid-America Apartment Communities", nameEn: "Mid-America Apartment Communities" },
  { symbol: "MRNA", nameKo: "모더나", nameEn: "Moderna" },
  { symbol: "TAP", nameKo: "Molson Coors Beverage", nameEn: "Molson Coors Beverage" },
  { symbol: "MDLZ", nameKo: "몬델리즈 인터내셔널", nameEn: "Mondelez International" },
  { symbol: "MPWR", nameKo: "Monolithic Power Systems", nameEn: "Monolithic Power Systems" },
  { symbol: "MNST", nameKo: "몬스터 베버리지", nameEn: "Monster Beverage" },
  { symbol: "MCO", nameKo: "무디스", nameEn: "Moody's" },
  { symbol: "MS", nameKo: "모건 스탠리", nameEn: "Morgan Stanley" },
  { symbol: "MOS", nameKo: "Mosaic", nameEn: "Mosaic" },
  { symbol: "MSI", nameKo: "모토로라 솔루션즈", nameEn: "Motorola Solutions" },
  { symbol: "MSCI", nameKo: "MSCI", nameEn: "MSCI" },
  { symbol: "NDAQ", nameKo: "나스닥", nameEn: "Nasdaq" },
  { symbol: "NTAP", nameKo: "NetApp", nameEn: "NetApp" },
  { symbol: "NFLX", nameKo: "넷플릭스", nameEn: "Netflix" },
  { symbol: "NEM", nameKo: "뉴몬트", nameEn: "Newmont" },
  { symbol: "NWSA", nameKo: "News Corp (Class A)", nameEn: "News Corp (Class A)" },
  { symbol: "NWS", nameKo: "News Corp (Class B)", nameEn: "News Corp (Class B)" },
  { symbol: "NEE", nameKo: "넥스트에라 에너지", nameEn: "NextEra Energy" },
  { symbol: "NKE", nameKo: "나이키", nameEn: "Nike" },
  { symbol: "NI", nameKo: "NiSource", nameEn: "NiSource" },
  { symbol: "NDSN", nameKo: "Nordson", nameEn: "Nordson" },
  { symbol: "NSC", nameKo: "노퍽 서던", nameEn: "Norfolk Southern" },
  { symbol: "NTRS", nameKo: "Northern Trust", nameEn: "Northern Trust" },
  { symbol: "NOC", nameKo: "노스롭 그루먼", nameEn: "Northrop Grumman" },
  { symbol: "NCLH", nameKo: "Norwegian Cruise Line Holdings", nameEn: "Norwegian Cruise Line Holdings" },
  { symbol: "NRG", nameKo: "NRG 에너지", nameEn: "NRG Energy" },
  { symbol: "NUE", nameKo: "뉴코", nameEn: "Nucor" },
  { symbol: "NVDA", nameKo: "엔비디아", nameEn: "Nvidia" },
  { symbol: "NVR", nameKo: "NVR", nameEn: "NVR" },
  { symbol: "NXPI", nameKo: "NXP 세미컨덕터스", nameEn: "NXP Semiconductors" },
  { symbol: "ORLY", nameKo: "O’Reilly Automotive", nameEn: "O’Reilly Automotive" },
  { symbol: "OXY", nameKo: "옥시덴탈 페트롤리엄", nameEn: "Occidental Petroleum" },
  { symbol: "ODFL", nameKo: "Old Dominion", nameEn: "Old Dominion" },
  { symbol: "OMC", nameKo: "옴니콤 그룹", nameEn: "Omnicom Group" },
  { symbol: "ON", nameKo: "온세미컨덕터", nameEn: "ON Semiconductor" },
  { symbol: "OKE", nameKo: "Oneok", nameEn: "Oneok" },
  { symbol: "ORCL", nameKo: "오라클", nameEn: "Oracle" },
  { symbol: "OTIS", nameKo: "오티스 월드와이드", nameEn: "Otis Worldwide" },
  { symbol: "PCAR", nameKo: "Paccar", nameEn: "Paccar" },
  { symbol: "PKG", nameKo: "Packaging Corporation of America", nameEn: "Packaging Corporation of America" },
  { symbol: "PLTR", nameKo: "Palantir Technologies", nameEn: "Palantir Technologies" },
  { symbol: "PANW", nameKo: "팔로알토 네트웍스", nameEn: "Palo Alto Networks" },
  { symbol: "PSKY", nameKo: "Paramount Skydance", nameEn: "Paramount Skydance" },
  { symbol: "PH", nameKo: "파커 하니핀", nameEn: "Parker Hannifin" },
  { symbol: "PAYX", nameKo: "페이첵스", nameEn: "Paychex" },
  { symbol: "PYPL", nameKo: "페이팔", nameEn: "PayPal" },
  { symbol: "PNR", nameKo: "Pentair", nameEn: "Pentair" },
  { symbol: "PEP", nameKo: "펩시코", nameEn: "PepsiCo" },
  { symbol: "PFE", nameKo: "화이자", nameEn: "Pfizer" },
  { symbol: "PCG", nameKo: "PG&E", nameEn: "PG&E" },
  { symbol: "PM", nameKo: "필립모리스 인터내셔널", nameEn: "Philip Morris International" },
  { symbol: "PSX", nameKo: "필립스 66", nameEn: "Phillips 66" },
  { symbol: "PNW", nameKo: "Pinnacle West Capital", nameEn: "Pinnacle West Capital" },
  { symbol: "PNC", nameKo: "PNC 파이낸셜 서비스", nameEn: "PNC Financial Services" },
  { symbol: "PPG", nameKo: "PPG 인더스트리즈", nameEn: "PPG Industries" },
  { symbol: "PPL", nameKo: "PPL", nameEn: "PPL" },
  { symbol: "PFG", nameKo: "Principal Financial Group", nameEn: "Principal Financial Group" },
  { symbol: "PG", nameKo: "프록터앤드갬블", nameEn: "Procter & Gamble" },
  { symbol: "PGR", nameKo: "프로그레시브", nameEn: "Progressive" },
  { symbol: "PLD", nameKo: "프로로지스", nameEn: "Prologis" },
  { symbol: "PRU", nameKo: "푸르덴셜 파이낸셜", nameEn: "Prudential Financial" },
  { symbol: "PEG", nameKo: "Public Service Enterprise Group", nameEn: "Public Service Enterprise Group" },
  { symbol: "PTC", nameKo: "PTC", nameEn: "PTC" },
  { symbol: "PSA", nameKo: "퍼블릭 스토리지", nameEn: "Public Storage" },
  { symbol: "PHM", nameKo: "PulteGroup", nameEn: "PulteGroup" },
  { symbol: "PWR", nameKo: "퀀타 서비스", nameEn: "Quanta Services" },
  { symbol: "QCOM", nameKo: "퀄컴", nameEn: "Qualcomm" },
  { symbol: "DGX", nameKo: "Quest Diagnostics", nameEn: "Quest Diagnostics" },
  { symbol: "Q", nameKo: "Qnity Electronics", nameEn: "Qnity Electronics" },
  { symbol: "RL", nameKo: "Ralph Lauren", nameEn: "Ralph Lauren" },
  { symbol: "RJF", nameKo: "Raymond James Financial", nameEn: "Raymond James Financial" },
  { symbol: "RTX", nameKo: "RTX", nameEn: "RTX" },
  { symbol: "O", nameKo: "리얼티 인컴", nameEn: "Realty Income" },
  { symbol: "REG", nameKo: "Regency Centers", nameEn: "Regency Centers" },
  { symbol: "REGN", nameKo: "리제네론 파마슈티컬스", nameEn: "Regeneron Pharmaceuticals" },
  { symbol: "RF", nameKo: "리전스 파이낸셜", nameEn: "Regions Financial" },
  { symbol: "RSG", nameKo: "Republic Services", nameEn: "Republic Services" },
  { symbol: "RMD", nameKo: "ResMed", nameEn: "ResMed" },
  { symbol: "RVTY", nameKo: "Revvity", nameEn: "Revvity" },
  { symbol: "HOOD", nameKo: "Robinhood Markets", nameEn: "Robinhood Markets" },
  { symbol: "ROK", nameKo: "록웰 오토메이션", nameEn: "Rockwell Automation" },
  { symbol: "ROL", nameKo: "Rollins", nameEn: "Rollins" },
  { symbol: "ROP", nameKo: "로퍼 테크놀로지스", nameEn: "Roper Technologies" },
  { symbol: "ROST", nameKo: "로스 스토어즈", nameEn: "Ross Stores" },
  { symbol: "RCL", nameKo: "로열 캐리비안 그룹", nameEn: "Royal Caribbean Group" },
  { symbol: "SPGI", nameKo: "S&P 글로벌", nameEn: "S&P Global" },
  { symbol: "CRM", nameKo: "세일즈포스", nameEn: "Salesforce" },
  { symbol: "SNDK", nameKo: "Sandisk", nameEn: "Sandisk" },
  { symbol: "SBAC", nameKo: "SBA Communications", nameEn: "SBA Communications" },
  { symbol: "SLB", nameKo: "슐럼버거", nameEn: "Schlumberger" },
  { symbol: "STX", nameKo: "Seagate Technology", nameEn: "Seagate Technology" },
  { symbol: "SRE", nameKo: "Sempra", nameEn: "Sempra" },
  { symbol: "NOW", nameKo: "서비스나우", nameEn: "ServiceNow" },
  { symbol: "SHW", nameKo: "셔윈-윌리엄스", nameEn: "Sherwin-Williams" },
  { symbol: "SPG", nameKo: "사이먼 프로퍼티 그룹", nameEn: "Simon Property Group" },
  { symbol: "SWKS", nameKo: "Skyworks Solutions", nameEn: "Skyworks Solutions" },
  { symbol: "SJM", nameKo: "J.M. Smucker", nameEn: "J.M. Smucker" },
  { symbol: "SW", nameKo: "Smurfit Westrock", nameEn: "Smurfit Westrock" },
  { symbol: "SNA", nameKo: "Snap-on", nameEn: "Snap-on" },
  { symbol: "SOLV", nameKo: "Solventum", nameEn: "Solventum" },
  { symbol: "SO", nameKo: "서던 컴퍼니", nameEn: "Southern" },
  { symbol: "LUV", nameKo: "사우스웨스트 항공", nameEn: "Southwest Airlines" },
  { symbol: "SWK", nameKo: "Stanley Black & Decker", nameEn: "Stanley Black & Decker" },
  { symbol: "SBUX", nameKo: "스타벅스", nameEn: "Starbucks" },
  { symbol: "STT", nameKo: "스테이트 스트리트", nameEn: "State Street" },
  { symbol: "STLD", nameKo: "Steel Dynamics", nameEn: "Steel Dynamics" },
  { symbol: "STE", nameKo: "Steris", nameEn: "Steris" },
  { symbol: "SYK", nameKo: "스트라이커", nameEn: "Stryker" },
  { symbol: "SMCI", nameKo: "Supermicro", nameEn: "Supermicro" },
  { symbol: "SYF", nameKo: "Synchrony Financial", nameEn: "Synchrony Financial" },
  { symbol: "SNPS", nameKo: "Synopsys", nameEn: "Synopsys" },
  { symbol: "SYY", nameKo: "Sysco", nameEn: "Sysco" },
  { symbol: "TMUS", nameKo: "T-모바일 US", nameEn: "T-Mobile US" },
  { symbol: "TROW", nameKo: "T. 로우 프라이스", nameEn: "T. Rowe Price" },
  { symbol: "TTWO", nameKo: "Take-Two Interactive", nameEn: "Take-Two Interactive" },
  { symbol: "TPR", nameKo: "Tapestry", nameEn: "Tapestry" },
  { symbol: "TRGP", nameKo: "Targa Resources", nameEn: "Targa Resources" },
  { symbol: "TGT", nameKo: "타겟", nameEn: "Target" },
  { symbol: "TEL", nameKo: "TE Connectivity", nameEn: "TE Connectivity" },
  { symbol: "TDY", nameKo: "Teledyne Technologies", nameEn: "Teledyne Technologies" },
  { symbol: "TER", nameKo: "Teradyne", nameEn: "Teradyne" },
  { symbol: "TSLA", nameKo: "테슬라", nameEn: "Tesla" },
  { symbol: "TXN", nameKo: "텍사스 인스트루먼트", nameEn: "Texas Instruments" },
  { symbol: "TPL", nameKo: "Texas Pacific Land", nameEn: "Texas Pacific Land" },
  { symbol: "TXT", nameKo: "텍스트론", nameEn: "Textron" },
  { symbol: "TMO", nameKo: "써모피셔 사이언티픽", nameEn: "Thermo Fisher Scientific" },
  { symbol: "TJX", nameKo: "TJX 컴퍼니즈", nameEn: "TJX Companies" },
  { symbol: "TKO", nameKo: "TKO Group Holdings", nameEn: "TKO Group Holdings" },
  { symbol: "TTD", nameKo: "Trade Desk", nameEn: "Trade Desk" },
  { symbol: "TSCO", nameKo: "트랙터 서플라이", nameEn: "Tractor Supply" },
  { symbol: "TT", nameKo: "Trane Technologies", nameEn: "Trane Technologies" },
  { symbol: "TDG", nameKo: "TransDigm Group", nameEn: "TransDigm Group" },
  { symbol: "TRV", nameKo: "트래블러스", nameEn: "Travelers Companies" },
  { symbol: "TRMB", nameKo: "Trimble", nameEn: "Trimble" },
  { symbol: "TFC", nameKo: "트루이스트 파이낸셜", nameEn: "Truist Financial" },
  { symbol: "TYL", nameKo: "Tyler Technologies", nameEn: "Tyler Technologies" },
  { symbol: "TSN", nameKo: "타이슨 푸드", nameEn: "Tyson Foods" },
  { symbol: "USB", nameKo: "US 뱅코프", nameEn: "U.S. Bancorp" },
  { symbol: "UBER", nameKo: "우버", nameEn: "Uber" },
  { symbol: "UDR", nameKo: "UDR", nameEn: "UDR" },
  { symbol: "ULTA", nameKo: "울타 뷰티", nameEn: "Ulta Beauty" },
  { symbol: "UNP", nameKo: "유니언 퍼시픽", nameEn: "Union Pacific" },
  { symbol: "UAL", nameKo: "유나이티드 항공", nameEn: "United Airlines Holdings" },
  { symbol: "UPS", nameKo: "UPS", nameEn: "United Parcel Service" },
  { symbol: "URI", nameKo: "United Rentals", nameEn: "United Rentals" },
  { symbol: "UNH", nameKo: "유나이티드헬스 그룹", nameEn: "UnitedHealth Group" },
  { symbol: "UHS", nameKo: "Universal Health Services", nameEn: "Universal Health Services" },
  { symbol: "VLO", nameKo: "발레로 에너지", nameEn: "Valero Energy" },
  { symbol: "VEEV", nameKo: "Veeva Systems", nameEn: "Veeva Systems" },
  { symbol: "VTR", nameKo: "Ventas", nameEn: "Ventas" },
  { symbol: "VLTO", nameKo: "Veralto", nameEn: "Veralto" },
  { symbol: "VRSN", nameKo: "Verisign", nameEn: "Verisign" },
  { symbol: "VRSK", nameKo: "Verisk Analytics", nameEn: "Verisk Analytics" },
  { symbol: "VZ", nameKo: "버라이즌", nameEn: "Verizon" },
  { symbol: "VRTX", nameKo: "버텍스 파마슈티컬스", nameEn: "Vertex Pharmaceuticals" },
  { symbol: "VRT", nameKo: "Vertiv", nameEn: "Vertiv" },
  { symbol: "VTRS", nameKo: "Viatris", nameEn: "Viatris" },
  { symbol: "VICI", nameKo: "Vici Properties", nameEn: "Vici Properties" },
  { symbol: "V", nameKo: "비자", nameEn: "Visa" },
  { symbol: "VST", nameKo: "Vistra", nameEn: "Vistra" },
  { symbol: "VMC", nameKo: "벌컨 머티리얼즈", nameEn: "Vulcan Materials" },
  { symbol: "WRB", nameKo: "W. R. Berkley", nameEn: "W. R. Berkley" },
  { symbol: "GWW", nameKo: "W.W. 그레인저", nameEn: "W. W. Grainger" },
  { symbol: "WAB", nameKo: "Wabtec", nameEn: "Wabtec" },
  { symbol: "WMT", nameKo: "월마트", nameEn: "Walmart" },
  { symbol: "DIS", nameKo: "월트 디즈니", nameEn: "Walt Disney" },
  { symbol: "WBD", nameKo: "워너브라더스 디스커버리", nameEn: "Warner Bros. Discovery" },
  { symbol: "WM", nameKo: "웨이스트 매니지먼트", nameEn: "Waste Management" },
  { symbol: "WAT", nameKo: "Waters", nameEn: "Waters" },
  { symbol: "WEC", nameKo: "WEC Energy Group", nameEn: "WEC Energy Group" },
  { symbol: "WFC", nameKo: "웰스파고", nameEn: "Wells Fargo" },
  { symbol: "WELL", nameKo: "Welltower", nameEn: "Welltower" },
  { symbol: "WST", nameKo: "West Pharmaceutical Services", nameEn: "West Pharmaceutical Services" },
  { symbol: "WDC", nameKo: "웨스턴 디지털", nameEn: "Western Digital" },
  { symbol: "WY", nameKo: "Weyerhaeuser", nameEn: "Weyerhaeuser" },
  { symbol: "WSM", nameKo: "Williams-Sonoma", nameEn: "Williams-Sonoma" },
  { symbol: "WMB", nameKo: "Williams Companies", nameEn: "Williams Companies" },
  { symbol: "WTW", nameKo: "Willis Towers Watson", nameEn: "Willis Towers Watson" },
  { symbol: "WDAY", nameKo: "Workday", nameEn: "Workday" },
  { symbol: "WYNN", nameKo: "윈 리조트", nameEn: "Wynn Resorts" },
  { symbol: "XEL", nameKo: "엑셀 에너지", nameEn: "Xcel Energy" },
  { symbol: "XYL", nameKo: "Xylem", nameEn: "Xylem" },
  { symbol: "YUM", nameKo: "얌 브랜즈", nameEn: "Yum! Brands" },
  { symbol: "ZBRA", nameKo: "지브라 테크놀로지스", nameEn: "Zebra Technologies" },
  { symbol: "ZBH", nameKo: "Zimmer Biomet", nameEn: "Zimmer Biomet" },
  { symbol: "ZTS", nameKo: "조에티스", nameEn: "Zoetis" },
]
